[profile.default]
solc = "0.8.17"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "src/=src/",
  "oz/=lib/openzeppelin-contracts/contracts/",
  "upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
]
evm_version = "shanghai"

[fmt]
line_length = 120
tab_width = 2
number_underscore = "thousands"
wrap_comments = true
